s3cmd put --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/* s3://risas.funnythings247.com/ --exclude='assets/' --exclude='page/' --exclude='images/' --exclude='sitemaps/' --exclude='nav/'
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/assets/* s3://risas.funnythings247.com/assets/ --add-header 'Cache-Control: public, max-age=31600000' 
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/10/* s3://risas.funnythings247.com/page/10/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/15/* s3://risas.funnythings247.com/page/15/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/20/* s3://risas.funnythings247.com/page/20/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/25/* s3://risas.funnythings247.com/page/25/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/2t/* s3://risas.funnythings247.com/page/2t/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/31/* s3://risas.funnythings247.com/page/31/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/35/* s3://risas.funnythings247.com/page/35/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/36/* s3://risas.funnythings247.com/page/36/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/3c/* s3://risas.funnythings247.com/page/3c/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/3m/* s3://risas.funnythings247.com/page/3m/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/3p/* s3://risas.funnythings247.com/page/3p/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/3v/* s3://risas.funnythings247.com/page/3v/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/48/* s3://risas.funnythings247.com/page/48/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/5m/* s3://risas.funnythings247.com/page/5m/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/5p/* s3://risas.funnythings247.com/page/5p/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/7p/* s3://risas.funnythings247.com/page/7p/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ab/* s3://risas.funnythings247.com/page/ab/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ac/* s3://risas.funnythings247.com/page/ac/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ai/* s3://risas.funnythings247.com/page/ai/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/al/* s3://risas.funnythings247.com/page/al/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/am/* s3://risas.funnythings247.com/page/am/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/an/* s3://risas.funnythings247.com/page/an/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ap/* s3://risas.funnythings247.com/page/ap/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/aq/* s3://risas.funnythings247.com/page/aq/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ar/* s3://risas.funnythings247.com/page/ar/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/as/* s3://risas.funnythings247.com/page/as/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/at/* s3://risas.funnythings247.com/page/at/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/au/* s3://risas.funnythings247.com/page/au/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/av/* s3://risas.funnythings247.com/page/av/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ay/* s3://risas.funnythings247.com/page/ay/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ba/* s3://risas.funnythings247.com/page/ba/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/be/* s3://risas.funnythings247.com/page/be/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/bi/* s3://risas.funnythings247.com/page/bi/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/bl/* s3://risas.funnythings247.com/page/bl/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/bo/* s3://risas.funnythings247.com/page/bo/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/br/* s3://risas.funnythings247.com/page/br/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/bu/* s3://risas.funnythings247.com/page/bu/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ca/* s3://risas.funnythings247.com/page/ca/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ce/* s3://risas.funnythings247.com/page/ce/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ch/* s3://risas.funnythings247.com/page/ch/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ci/* s3://risas.funnythings247.com/page/ci/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/cl/* s3://risas.funnythings247.com/page/cl/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/cm/* s3://risas.funnythings247.com/page/cm/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/co/* s3://risas.funnythings247.com/page/co/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/cr/* s3://risas.funnythings247.com/page/cr/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/cu/* s3://risas.funnythings247.com/page/cu/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/da/* s3://risas.funnythings247.com/page/da/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/de/* s3://risas.funnythings247.com/page/de/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/di/* s3://risas.funnythings247.com/page/di/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/dj/* s3://risas.funnythings247.com/page/dj/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/dn/* s3://risas.funnythings247.com/page/dn/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/do/* s3://risas.funnythings247.com/page/do/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/du/* s3://risas.funnythings247.com/page/du/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ef/* s3://risas.funnythings247.com/page/ef/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ej/* s3://risas.funnythings247.com/page/ej/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/el/* s3://risas.funnythings247.com/page/el/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/en/* s3://risas.funnythings247.com/page/en/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/er/* s3://risas.funnythings247.com/page/er/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/es/* s3://risas.funnythings247.com/page/es/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ev/* s3://risas.funnythings247.com/page/ev/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ex/* s3://risas.funnythings247.com/page/ex/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/fa/* s3://risas.funnythings247.com/page/fa/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/fe/* s3://risas.funnythings247.com/page/fe/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/fi/* s3://risas.funnythings247.com/page/fi/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/fl/* s3://risas.funnythings247.com/page/fl/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/fo/* s3://risas.funnythings247.com/page/fo/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/fr/* s3://risas.funnythings247.com/page/fr/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ft/* s3://risas.funnythings247.com/page/ft/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/fu/* s3://risas.funnythings247.com/page/fu/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ga/* s3://risas.funnythings247.com/page/ga/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ge/* s3://risas.funnythings247.com/page/ge/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/gi/* s3://risas.funnythings247.com/page/gi/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/gl/* s3://risas.funnythings247.com/page/gl/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/go/* s3://risas.funnythings247.com/page/go/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/gr/* s3://risas.funnythings247.com/page/gr/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/gu/* s3://risas.funnythings247.com/page/gu/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ha/* s3://risas.funnythings247.com/page/ha/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/he/* s3://risas.funnythings247.com/page/he/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/hi/* s3://risas.funnythings247.com/page/hi/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ho/* s3://risas.funnythings247.com/page/ho/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/hu/* s3://risas.funnythings247.com/page/hu/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/id/* s3://risas.funnythings247.com/page/id/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ig/* s3://risas.funnythings247.com/page/ig/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/im/* s3://risas.funnythings247.com/page/im/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/in/* s3://risas.funnythings247.com/page/in/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ir/* s3://risas.funnythings247.com/page/ir/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ja/* s3://risas.funnythings247.com/page/ja/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ju/* s3://risas.funnythings247.com/page/ju/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ka/* s3://risas.funnythings247.com/page/ka/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ki/* s3://risas.funnythings247.com/page/ki/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/la/* s3://risas.funnythings247.com/page/la/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/le/* s3://risas.funnythings247.com/page/le/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/li/* s3://risas.funnythings247.com/page/li/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ll/* s3://risas.funnythings247.com/page/ll/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/lo/* s3://risas.funnythings247.com/page/lo/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ma/* s3://risas.funnythings247.com/page/ma/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/md/* s3://risas.funnythings247.com/page/md/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/me/* s3://risas.funnythings247.com/page/me/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/mi/* s3://risas.funnythings247.com/page/mi/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/mo/* s3://risas.funnythings247.com/page/mo/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/mq/* s3://risas.funnythings247.com/page/mq/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ms/* s3://risas.funnythings247.com/page/ms/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/mu/* s3://risas.funnythings247.com/page/mu/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/na/* s3://risas.funnythings247.com/page/na/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/nb/* s3://risas.funnythings247.com/page/nb/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ne/* s3://risas.funnythings247.com/page/ne/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ni/* s3://risas.funnythings247.com/page/ni/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/no/* s3://risas.funnythings247.com/page/no/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/nu/* s3://risas.funnythings247.com/page/nu/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/od/* s3://risas.funnythings247.com/page/od/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ol/* s3://risas.funnythings247.com/page/ol/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/or/* s3://risas.funnythings247.com/page/or/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/os/* s3://risas.funnythings247.com/page/os/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ot/* s3://risas.funnythings247.com/page/ot/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ov/* s3://risas.funnythings247.com/page/ov/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/pa/* s3://risas.funnythings247.com/page/pa/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/pe/* s3://risas.funnythings247.com/page/pe/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/pi/* s3://risas.funnythings247.com/page/pi/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/pj/* s3://risas.funnythings247.com/page/pj/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/pl/* s3://risas.funnythings247.com/page/pl/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/po/* s3://risas.funnythings247.com/page/po/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/pr/* s3://risas.funnythings247.com/page/pr/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/pu/* s3://risas.funnythings247.com/page/pu/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/qu/* s3://risas.funnythings247.com/page/qu/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ra/* s3://risas.funnythings247.com/page/ra/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/rb/* s3://risas.funnythings247.com/page/rb/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/re/* s3://risas.funnythings247.com/page/re/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ri/* s3://risas.funnythings247.com/page/ri/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ro/* s3://risas.funnythings247.com/page/ro/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ru/* s3://risas.funnythings247.com/page/ru/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/sa/* s3://risas.funnythings247.com/page/sa/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/sb/* s3://risas.funnythings247.com/page/sb/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/se/* s3://risas.funnythings247.com/page/se/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/sh/* s3://risas.funnythings247.com/page/sh/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/si/* s3://risas.funnythings247.com/page/si/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/sk/* s3://risas.funnythings247.com/page/sk/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/sl/* s3://risas.funnythings247.com/page/sl/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/so/* s3://risas.funnythings247.com/page/so/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/sp/* s3://risas.funnythings247.com/page/sp/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/st/* s3://risas.funnythings247.com/page/st/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/su/* s3://risas.funnythings247.com/page/su/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ta/* s3://risas.funnythings247.com/page/ta/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/tc/* s3://risas.funnythings247.com/page/tc/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/te/* s3://risas.funnythings247.com/page/te/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ti/* s3://risas.funnythings247.com/page/ti/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/to/* s3://risas.funnythings247.com/page/to/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/tr/* s3://risas.funnythings247.com/page/tr/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/tu/* s3://risas.funnythings247.com/page/tu/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/tw/* s3://risas.funnythings247.com/page/tw/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/un/* s3://risas.funnythings247.com/page/un/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/va/* s3://risas.funnythings247.com/page/va/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ve/* s3://risas.funnythings247.com/page/ve/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/vi/* s3://risas.funnythings247.com/page/vi/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/vo/* s3://risas.funnythings247.com/page/vo/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/vu/* s3://risas.funnythings247.com/page/vu/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/wi/* s3://risas.funnythings247.com/page/wi/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/wt/* s3://risas.funnythings247.com/page/wt/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ya/* s3://risas.funnythings247.com/page/ya/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/yo/* s3://risas.funnythings247.com/page/yo/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/ys/* s3://risas.funnythings247.com/page/ys/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/page/za/* s3://risas.funnythings247.com/page/za/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/nav/* s3://risas.funnythings247.com/nav/
s3cmd sync --acl-public --guess-mime-type -P ./public//risas.funnythings247.com/sitemaps/* s3://risas.funnythings247.com/sitemaps/
