s3cmd put --acl-public --guess-mime-type -P ./public//funnythings247.com/* s3://funnythings247.com/ --exclude='assets/' --exclude='page/' --exclude='images/' --exclude='sitemaps/' --exclude='nav/'
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/assets/* s3://funnythings247.com/assets/ --add-header 'Cache-Control: public, max-age=31600000' 
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ab/* s3://funnythings247.com/page/ab/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ac/* s3://funnythings247.com/page/ac/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ad/* s3://funnythings247.com/page/ad/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ah/* s3://funnythings247.com/page/ah/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ak/* s3://funnythings247.com/page/ak/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/am/* s3://funnythings247.com/page/am/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/an/* s3://funnythings247.com/page/an/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ar/* s3://funnythings247.com/page/ar/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/as/* s3://funnythings247.com/page/as/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/at/* s3://funnythings247.com/page/at/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/aw/* s3://funnythings247.com/page/aw/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ax/* s3://funnythings247.com/page/ax/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ba/* s3://funnythings247.com/page/ba/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/be/* s3://funnythings247.com/page/be/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/bi/* s3://funnythings247.com/page/bi/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/bu/* s3://funnythings247.com/page/bu/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ca/* s3://funnythings247.com/page/ca/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ch/* s3://funnythings247.com/page/ch/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ci/* s3://funnythings247.com/page/ci/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/co/* s3://funnythings247.com/page/co/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/cu/* s3://funnythings247.com/page/cu/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/da/* s3://funnythings247.com/page/da/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/de/* s3://funnythings247.com/page/de/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/do/* s3://funnythings247.com/page/do/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/du/* s3://funnythings247.com/page/du/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ep/* s3://funnythings247.com/page/ep/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ev/* s3://funnythings247.com/page/ev/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/fa/* s3://funnythings247.com/page/fa/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/fe/* s3://funnythings247.com/page/fe/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/fi/* s3://funnythings247.com/page/fi/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/fo/* s3://funnythings247.com/page/fo/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/fr/* s3://funnythings247.com/page/fr/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/fu/* s3://funnythings247.com/page/fu/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ga/* s3://funnythings247.com/page/ga/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ge/* s3://funnythings247.com/page/ge/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/gi/* s3://funnythings247.com/page/gi/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/go/* s3://funnythings247.com/page/go/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ha/* s3://funnythings247.com/page/ha/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/he/* s3://funnythings247.com/page/he/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ho/* s3://funnythings247.com/page/ho/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/hu/* s3://funnythings247.com/page/hu/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ig/* s3://funnythings247.com/page/ig/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ih/* s3://funnythings247.com/page/ih/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/im/* s3://funnythings247.com/page/im/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/in/* s3://funnythings247.com/page/in/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/is/* s3://funnythings247.com/page/is/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/it/* s3://funnythings247.com/page/it/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/iv/* s3://funnythings247.com/page/iv/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ju/* s3://funnythings247.com/page/ju/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ki/* s3://funnythings247.com/page/ki/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/li/* s3://funnythings247.com/page/li/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/lo/* s3://funnythings247.com/page/lo/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ma/* s3://funnythings247.com/page/ma/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/me/* s3://funnythings247.com/page/me/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/mi/* s3://funnythings247.com/page/mi/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/my/* s3://funnythings247.com/page/my/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/no/* s3://funnythings247.com/page/no/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/oh/* s3://funnythings247.com/page/oh/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ol/* s3://funnythings247.com/page/ol/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/on/* s3://funnythings247.com/page/on/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/or/* s3://funnythings247.com/page/or/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/pa/* s3://funnythings247.com/page/pa/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/pe/* s3://funnythings247.com/page/pe/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/po/* s3://funnythings247.com/page/po/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/pr/* s3://funnythings247.com/page/pr/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/qu/* s3://funnythings247.com/page/qu/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ri/* s3://funnythings247.com/page/ri/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/sa/* s3://funnythings247.com/page/sa/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/sh/* s3://funnythings247.com/page/sh/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/si/* s3://funnythings247.com/page/si/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/sl/* s3://funnythings247.com/page/sl/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/so/* s3://funnythings247.com/page/so/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/sp/* s3://funnythings247.com/page/sp/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/st/* s3://funnythings247.com/page/st/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/su/* s3://funnythings247.com/page/su/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/sw/* s3://funnythings247.com/page/sw/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/te/* s3://funnythings247.com/page/te/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/th/* s3://funnythings247.com/page/th/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/tu/* s3://funnythings247.com/page/tu/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/tw/* s3://funnythings247.com/page/tw/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/un/* s3://funnythings247.com/page/un/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ve/* s3://funnythings247.com/page/ve/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/we/* s3://funnythings247.com/page/we/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/wh/* s3://funnythings247.com/page/wh/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/wi/* s3://funnythings247.com/page/wi/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/wo/* s3://funnythings247.com/page/wo/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/wr/* s3://funnythings247.com/page/wr/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ya/* s3://funnythings247.com/page/ya/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/ye/* s3://funnythings247.com/page/ye/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/yo/* s3://funnythings247.com/page/yo/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/page/zo/* s3://funnythings247.com/page/zo/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/nav/* s3://funnythings247.com/nav/
s3cmd sync --acl-public --guess-mime-type -P ./public//funnythings247.com/sitemaps/* s3://funnythings247.com/sitemaps/
