s3cmd sync --acl-public --guess-mime-type -P ./public/page/ad/* s3://funnythings247.com/page/ad/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/ai/* s3://funnythings247.com/page/ai/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/am/* s3://funnythings247.com/page/am/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/an/* s3://funnythings247.com/page/an/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/as/* s3://funnythings247.com/page/as/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/at/* s3://funnythings247.com/page/at/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/av/* s3://funnythings247.com/page/av/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/aw/* s3://funnythings247.com/page/aw/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/b0/* s3://funnythings247.com/page/b0/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/ba/* s3://funnythings247.com/page/ba/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/be/* s3://funnythings247.com/page/be/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/bi/* s3://funnythings247.com/page/bi/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/bu/* s3://funnythings247.com/page/bu/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/ca/* s3://funnythings247.com/page/ca/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/co/* s3://funnythings247.com/page/co/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/cy/* s3://funnythings247.com/page/cy/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/da/* s3://funnythings247.com/page/da/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/di/* s3://funnythings247.com/page/di/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/do/* s3://funnythings247.com/page/do/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/du/* s3://funnythings247.com/page/du/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/em/* s3://funnythings247.com/page/em/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/ep/* s3://funnythings247.com/page/ep/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/ev/* s3://funnythings247.com/page/ev/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/fa/* s3://funnythings247.com/page/fa/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/fe/* s3://funnythings247.com/page/fe/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/fo/* s3://funnythings247.com/page/fo/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/fr/* s3://funnythings247.com/page/fr/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/ga/* s3://funnythings247.com/page/ga/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/gi/* s3://funnythings247.com/page/gi/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/gu/* s3://funnythings247.com/page/gu/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/ha/* s3://funnythings247.com/page/ha/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/he/* s3://funnythings247.com/page/he/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/hi/* s3://funnythings247.com/page/hi/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/ho/* s3://funnythings247.com/page/ho/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/ia/* s3://funnythings247.com/page/ia/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/if/* s3://funnythings247.com/page/if/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/im/* s3://funnythings247.com/page/im/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/in/* s3://funnythings247.com/page/in/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/is/* s3://funnythings247.com/page/is/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/it/* s3://funnythings247.com/page/it/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/je/* s3://funnythings247.com/page/je/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/jo/* s3://funnythings247.com/page/jo/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/ju/* s3://funnythings247.com/page/ju/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/ki/* s3://funnythings247.com/page/ki/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/le/* s3://funnythings247.com/page/le/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/lo/* s3://funnythings247.com/page/lo/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/ma/* s3://funnythings247.com/page/ma/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/me/* s3://funnythings247.com/page/me/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/mi/* s3://funnythings247.com/page/mi/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/mo/* s3://funnythings247.com/page/mo/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/mu/* s3://funnythings247.com/page/mu/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/my/* s3://funnythings247.com/page/my/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/na/* s3://funnythings247.com/page/na/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/no/* s3://funnythings247.com/page/no/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/oh/* s3://funnythings247.com/page/oh/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/on/* s3://funnythings247.com/page/on/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/oo/* s3://funnythings247.com/page/oo/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/or/* s3://funnythings247.com/page/or/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/pe/* s3://funnythings247.com/page/pe/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/pi/* s3://funnythings247.com/page/pi/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/pl/* s3://funnythings247.com/page/pl/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/po/* s3://funnythings247.com/page/po/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/pr/* s3://funnythings247.com/page/pr/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/re/* s3://funnythings247.com/page/re/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/ru/* s3://funnythings247.com/page/ru/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/sc/* s3://funnythings247.com/page/sc/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/se/* s3://funnythings247.com/page/se/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/sh/* s3://funnythings247.com/page/sh/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/so/* s3://funnythings247.com/page/so/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/sp/* s3://funnythings247.com/page/sp/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/st/* s3://funnythings247.com/page/st/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/ta/* s3://funnythings247.com/page/ta/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/th/* s3://funnythings247.com/page/th/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/ti/* s3://funnythings247.com/page/ti/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/to/* s3://funnythings247.com/page/to/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/tv/* s3://funnythings247.com/page/tv/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/tw/* s3://funnythings247.com/page/tw/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/ty/* s3://funnythings247.com/page/ty/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/wa/* s3://funnythings247.com/page/wa/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/we/* s3://funnythings247.com/page/we/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/wh/* s3://funnythings247.com/page/wh/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/wo/* s3://funnythings247.com/page/wo/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/wt/* s3://funnythings247.com/page/wt/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/xg/* s3://funnythings247.com/page/xg/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/xm/* s3://funnythings247.com/page/xm/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/ye/* s3://funnythings247.com/page/ye/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/yo/* s3://funnythings247.com/page/yo/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/zo/* s3://funnythings247.com/page/zo/
s3cmd sync --acl-public --guess-mime-type -P ./public/page/* s3://funnythings247.com/page/
s3cmd sync --acl-public --guess-mime-type -P ./public/assets/* s3://funnythings247.com/assets/ --add-header 'Cache-Control: public, max-age=31600000' 
s3cmd sync --acl-public --guess-mime-type -P ./public/* s3://funnythings247.com/ --exclude='assets/' --exclude='page/' --exclude='images/'
